sudo: required

language: php

services:
- docker

#Target PHP versions
php:
 - 7.0
  
script:
  - docker run -ti docker pull pierre42100/docker-comunicwebappscratch git clone https://github.com/testpierre/ComunicWeb webapp; webapp/builder build offline
  
