sudo: required

language: php

services:
- docker

#Target PHP versions
php:
 - 7.0
 - 7.1
 - 7.2
  
script:
  - docker run -t -v $(pwd):/data pierre42100/docker-comunicwebappscratch /data/builder build offline
